# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fourth Seminar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fourth Seminar
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'lottie-ios'
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher', '~> 6.0'
end
